### PR TITLE
Add Subtask Description plugin.

### PR DESCRIPTION
**Pull request by Shaun-Fong**

### CODE REVIEW

**Comment by creecros** [comment]
This plugin confuses me. It's almost like I wrote it, and my name is associated with it and I don't quite understand the objective.
Can we at least remove my name?
https://github.com/Shaun-Fong/SubtaskDescription/blob/a15b04cfbaece28b6f7fab1a99a128168284fb2f/Api/Procedure/NewSubtaskProcedure.php#L13

**Comment by Shaun-Fong** [comment]
> This plugin confuses me. It's almost like I wrote it, and my name is associated with it and I don't quite understand the objective. Can we at least remove my name? https://github.com/Shaun-Fong/SubtaskDescription/blob/a15b04cfbaece28b6f7fab1a99a128168284fb2f/Api/Procedure/NewSubtaskProcedure.php#L13

My teammates said that the subtask needs this description feature very much.
lol , I think that's fine . oh if you want to remove your name i'll do it.
check this out [README](https://github.com/Shaun-Fong/SubtaskDescription/blob/main/README.md)
Plugin is base on [Subtaskdate](https://github.com/eSkiSo/Subtaskdate) .

**Comment by creecros** [comment]
my confusion comes with the plugin overriding the api provided, and using the same api call. it wouldn't add due date description, instead it would replace due date with description. have you tested this? I specifically mean the api, have you tested that?

if you just wanted to add a description, I think you may have misunderstood the api and how it works. 

ya, looking at it now, I'm thinking you didn't understand the point of the api procedures, and how by altering them, you made it impossible to actually use the api to include an actual date associated with a subtask. 

do you really need a plugin for a plugin? could have just made a PR. 

I know you think it's fine, but I think you only think that because you aren't using the api. I think if someone who isn't paying attention installs this, and needs to use the api, is going to have a lot of troubleshooting when it doesn't work the way they expect it to work. happy to explain and help you out if it's not clear to you. I was joking about my name, but found it funny when I saw the plugin and immediately recognized my code...

**Comment by Shaun-Fong** [comment]
> my confusion comes with the plugin overriding the api provided, and using the same api call. it wouldn't add due date description, instead it would replace due date with description. have you tested this? I specifically mean the api, have you tested that?

Nope , I didnt LOL.

> 
> if you just wanted to add a description, I think you may have misunderstood the api and how it works.
> 
> ya, looking at it now, I'm thinking you didn't understand the point of the api procedures, and how by altering them, you made it impossible to actually use the api to include an actual date associated with a subtask.

I just used this kanboard last week , you right I haven't understood all the source code yet. 

> 
> do you really need a plugin for a plugin? could have just made a PR.

I just did a very simple job (ctrl cv things). I think maybe someone needs this plugin, so I made this pr. or maybe you could help me to improve code?

> 
> I know you think it's fine, but I think you only think that because you aren't using the api. I think if someone who isn't paying attention installs this, and needs to use the api, is going to have a lot of troubleshooting when it doesn't work the way they expect it to work. happy to explain and help you out if it's not clear to you. I was joking about my name, but found it funny when I saw the plugin and immediately recognized my code...

thanks for reply

**Pull request merged**
