### PR TITLE
MetaMagik, Customizer, Group_assign update versions 

### PR DESCRIPTION
**Pull request by creecros**
## creecros/Customizer
- Additions:
  - Ability to add custom note to login screen
- Fixes: 
  - Centers the "Forgot password?" link in panel
  - "Forgot password?" link was missing from live preview, added

## creecros/MetaMagik
- Additions:
  - creecros/MetaMagik#44 Performance improvement to board

## creecros/Group_assign
- Additions:
  - creecros/Group_assign#45 Adds filter bar support
  - Maintaining compatibility with MetaMagik

## Notice
- Latest version of MetaMagik could break Group_assign functionality due to both plugins now override the TaskFinderModel. 
- Please update both plugins if you use them both.

### CODE REVIEW

**Comment by fguillot** [comment]
Can you please update the commit title to reflect what plugins your are updating instead of `Update plugins.json`? You can also provide the details above in the commit body. Thanks

**Comment by creecros** [comment]
All set

**Comment by fguillot** [comment]
The commit title, not the pull-request title :)

**Comment by creecros** [comment]
Surely, you know I'm bad at this, by now! :) I have no idea how to change the commit title.

**Pull request merged**
