### PR TITLE
Correcting GitHub download url for Greenwing

### PR DESCRIPTION
**Pull request by ChrisCarini**

### CODE REVIEW

**Review by aljawaid — CHANGES_REQUESTED** [review]
This download link is incorect. It will cause issues for user to install and update.

**Comment by ChrisCarini** [comment]
@aljawaid - Thanks for the prompt response!

When I try to install the `Greenwing` plugin, I get an error stating `Unable to open plugin archive.` - other plugins appear to work without issue. This lead me to try the download url in this JSON file.

Currently, the file has `https://github.com/Confexion/Greenwing/releases/download/1.3.2/Greenwing.zip`, which redirects to `https://github.com/p0lym0rphik/Greenwing/releases/download/1.3.2/Greenwing.zip`, which ultimately yields a 404:
```
$ > curl -i https://github.com/p0lym0rphik/Greenwing/releases/download/1.3.2/Greenwing.zip
HTTP/2 404 
server: GitHub.com
date: Wed, 28 Dec 2022 04:03:23 GMT
content-type: text/plain; charset=utf-8
vary: X-PJAX, X-PJAX-Container, Turbo-Visit, Turbo-Frame, Accept-Encoding, Accept, X-Requested-With
cache-control: no-cache
strict-transport-security: max-age=31536000; includeSubdomains; preload
x-frame-options: deny
x-content-type-options: nosniff
x-xss-protection: 0
referrer-policy: no-referrer-when-downgrade
content-security-policy: default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'
content-length: 9
x-github-request-id: <redacted>

Not Found
```

Going to the releases page for version 1.3.2 ([ref](https://github.com/p0lym0rphik/Greenwing/releases/tag/1.3.2)) shows the download of the zip archive to be: `https://github.com/p0lym0rphik/Greenwing/archive/refs/tags/1.3.2.zip`, when using this in a browser, a zip archive successfully downloads.

I had assumed the error I was getting was due to the fact that the URL was incorrect. I am fairly new to this project, so I'd appreciate more specific guidance / details as to what the correct URL would be (if it is the current one, why it should work from w/in the app when it does not appear to work elsewhere; perhaps kanboard does some special parsing / manipulation of the url before it makes the actual request?), and/or what issues might be caused :)

**Comment by aljawaid** [comment]
> I had assumed the error I was getting was due to the fact that the URL was incorrect. I am fairly new to this project, so I'd appreciate more specific guidance / details as to what the correct URL would be (if it is the current one, why it should work from w/in the app when it does not appear to work elsewhere; perhaps kanboard does some special parsing / manipulation of the url before it makes the actual request?), and/or what issues might be caused :)

Hello, no worries... so basically, if you leave it to github and use the archives that it generate on release, then use that for the plugins.json download link.... you get the problem you have mentioned.  That's because github adds the branch name to the folder name in the `.zip` file.  **Kanboard needs the folder name to match the plugin name.**

So to solve it, what I do, probably what others do in similar ways also if on windows.... create the `.zip` file of the plugin folder in windows and upload it to the github release.... then use that as the download link in `plugins.json` which works fine for installing and for updating when versions of the plugin has changed.

**Comment by ChrisCarini** [comment]
Ah interesting, ok. So it sounds like the plugin owner (not me, in the case of Greenwing) needs to make the zip in the necessary format, is that correct? Sounds like I might be out of luck for the time being, then. :(

**Comment by aljawaid** [comment]
> Going to the releases page for version 1.3.2 ([ref](https://github.com/p0lym0rphik/Greenwing/releases/tag/1.3.2)) shows the download of the zip archive to be: `https://github.com/p0lym0rphik/Greenwing/archive/refs/tags/1.3.2.zip`, when using this in a browser, a zip archive successfully downloads.
> 
Exactly, open that zip file and look at the folder name, its got the version number at the end of it.  The folder name should be `Greenwing` which is the same as the plugin name... but in this archive the structure of the file is all different to what a release would normally look like... so I would say follow my previous comment which is the same as what I tried to explain on the readme of this repository.

**Comment by aljawaid** [comment]
> Ah interesting, ok. So it sounds like the plugin owner (not me, in the case of Greenwing) needs to make the zip in the necessary format, is that correct? Sounds like I might be out of luck for the time being, then. :(

yes... unless you want to improve the plugin, rename it and then submit it as a new plugin.... otherwise make a pull request to the owner of the plugin in their respository

**Comment by ChrisCarini** [comment]
Thanks for all the detail, @aljawaid !

I'll go ahead and close out this PR given what you've educated me on - really appreciate it!

One final question for you, if you don't mind 😄 - would it make sense for https://github.com/kanboard/kanboard to support the default release zip for GitHub (and, possibly others like GitLab) so that there is less work by plugin owners? Based on what I understand (from both your responses, plus looking into the respective code a bit), it sounds like the logic of kanboard would just need to accommodate unzipping a directory w/ the version in the directory name, and move that into a directory with just the name of the plugin.

Thank you, again! 😄

**Comment by aljawaid** [comment]
> Thanks for all the detail, @aljawaid !
> 
> I'll go ahead and close out this PR given what you've educated me on - really appreciate it!
> 
> One final question for you, if you don't mind 😄 - would it make sense for https://github.com/kanboard/kanboard to support the default release zip for GitHub (and, possibly others like GitLab) so that there is less work by plugin owners? Based on what I understand (from both your responses, plus looking into the respective code a bit), it sounds like the logic of kanboard would just need to accommodate unzipping a directory w/ the version in the directory name, and move that into a directory with just the name of the plugin.
> 
> Thank you, again! 😄

It would make a lot of sense...but the developer has got Kanboard in maintanence mode needlessly, the UI alone is far behind the expectations of the professional industry yet the developer thinks that is fine. The docs alone, make it very difficult for othr developers to make plugins and sadly, as soon as the main developer put the repo in maintenance mode, most other plugin developers abandoned updating their plugins and moved on.  This was not good for kanboard at all. So basically if youre expecting any core changes, good luck, it is common in this respoitory for the developer to close issues and refer to the inactive forum.

**Comment by ChrisCarini** [comment]
I see, thats a bit of a bummer to hear. Is there an alternative project/app that you'd recommend, then? Mostly just curious..

**Comment by aljawaid** [comment]
No that's the issue. Kanboard itself is fantastic. We just got to hope it doesn't get abandoned. Just a shame that everything gets pushed to plugins.

**Pull request closed without merging**
